### ISSUE TITLE
宝塔里面项目日志没报错 也运行起来了 就是打不开网页

### ISSUE THREAD

**Issue by YuFengShiSan** [wyt1215819315/autoplan#41]
. ____ _ __ _ _
/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/ ___)| |_)| | | | | || (_| | ) ) ) )
' |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot :: (v2.6.3)

2022-03-24 10:00:39.127 INFO 1708642 --- [ main] com.AutoPlanApplication : Starting AutoPlanApplication v0.0.1-SNAPSHOT using Java 1.8.0_312 on VM-20-5-centos with PID 1708642 (/www/wwwroot/auto_plan.jar started by springboot in /www/wwwroot)
2022-03-24 10:00:39.130 INFO 1708642 --- [ main] com.AutoPlanApplication : No active profile set, falling back to default profiles: default
2022-03-24 10:00:41.108 INFO 1708642 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat initialized with port(s): 26666 (http)
2022-03-24 10:00:41.118 INFO 1708642 --- [ main] o.apache.catalina.core.StandardService : Starting service [Tomcat]
2022-03-24 10:00:41.119 INFO 1708642 --- [ main] org.apache.catalina.core.StandardEngine : Starting Servlet engine: [Apache Tomcat/9.0.56]
2022-03-24 10:00:41.184 INFO 1708642 --- [ main] o.a.c.c.C.[Tomcat].[localhost].[/] : Initializing Spring embedded WebApplicationContext
2022-03-24 10:00:41.184 INFO 1708642 --- [ main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1987 ms
_ _ |_ _ _|_. ___ _ | _
| | |\/|_)(_| | |_\ |_)||_|_\
/ |
3.4.3.4
2022-03-24 10:00:42.340 INFO 1708642 --- [ main] org.quartz.impl.StdSchedulerFactory : Using default implementation for ThreadExecutor
2022-03-24 10:00:42.343 INFO 1708642 --- [ main] org.quartz.simpl.SimpleThreadPool : Job execution threads will use class loader of thread: main
2022-03-24 10:00:42.368 INFO 1708642 --- [ main] org.quartz.core.SchedulerSignalerImpl : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2022-03-24 10:00:42.368 INFO 1708642 --- [ main] org.quartz.core.QuartzScheduler : Quartz Scheduler v.2.3.2 created.
2022-03-24 10:00:42.369 INFO 1708642 --- [ main] org.quartz.simpl.RAMJobStore : RAMJobStore initialized.
2022-03-24 10:00:42.370 INFO 1708642 --- [ main] org.quartz.core.QuartzScheduler : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
NOT STARTED.
Currently in standby mode.
Number of jobs executed: 0
Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2022-03-24 10:00:42.370 INFO 1708642 --- [ main] org.quartz.impl.StdSchedulerFactory : Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2022-03-24 10:00:42.370 INFO 1708642 --- [ main] org.quartz.impl.StdSchedulerFactory : Quartz scheduler version: 2.3.2
2022-03-24 10:00:42.414 INFO 1708642 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Starting...
2022-03-24 10:00:42.630 INFO 1708642 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Start completed.
2022-03-24 10:00:42.695 INFO 1708642 --- [ main] org.quartz.core.QuartzScheduler : Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2022-03-24 10:00:42.865 INFO 1708642 --- [ main] c.g.s.m.a.m.handler.StartUpHandlerImpl : databaseType=mysql，开始执行mysql的处理方法
2022-03-24 10:00:43.376 INFO 1708642 --- [ main] o.s.s.web.DefaultSecurityFilterChain : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@49c90a9c, org.springframework.security.web.context.SecurityContextPersistenceFilter@69504ae9, org.springframework.security.web.header.HeaderWriterFilter@2657d4dd, org.springframework.security.web.authentication.logout.LogoutFilter@5c7bfdc1, com.oldwu.security.validate.ValidateCodeFilter@1165b38, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@1f9f6368, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@28cda624, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@7eecb5b8, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@2d29b4ee, org.springframework.security.web.session.SessionManagementFilter@47caedad, org.springframework.security.web.access.ExceptionTranslationFilter@446a1e84, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@7486b455]
2022-03-24 10:00:43.663 INFO 1708642 --- [ main] o.s.b.a.w.s.WelcomePageHandlerMapping : Adding welcome page template: index
2022-03-24 10:00:43.923 INFO 1708642 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat started on port(s): 26666 (http) with context path ''
2022-03-24 10:00:43.936 INFO 1708642 --- [ main] com.AutoPlanApplication : Started AutoPlanApplication in 5.429 seconds (JVM running for 5.92)

---------上面的日志是宝塔里面的日志-------下面的日志是我服务器手动启动项目报错-------

.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-03-24 10:01:56.107  INFO 1712661 --- [           main] com.AutoPlanApplication                  : Starting AutoPlanApplication v0.0.1-SNAPSHOT using Java 1.8.0_312 on VM-20-5-centos with PID 1712661 (/www/wwwroot/auto_plan.jar started by root in /www/wwwroot)
2022-03-24 10:01:56.110  INFO 1712661 --- [           main] com.AutoPlanApplication                  : No active profile set, falling back to default profiles: default
2022-03-24 10:01:58.186  INFO 1712661 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 26666 (http)
2022-03-24 10:01:58.198  INFO 1712661 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-03-24 10:01:58.199  INFO 1712661 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.56]
2022-03-24 10:01:58.254  INFO 1712661 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-03-24 10:01:58.254  INFO 1712661 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2054 ms
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.4.3.4 
2022-03-24 10:01:59.424  INFO 1712661 --- [           main] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
2022-03-24 10:01:59.431  INFO 1712661 --- [           main] org.quartz.simpl.SimpleThreadPool        : Job execution threads will use class loader of thread: main
2022-03-24 10:01:59.467  INFO 1712661 --- [           main] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2022-03-24 10:01:59.467  INFO 1712661 --- [           main] org.quartz.core.QuartzScheduler          : Quartz Scheduler v.2.3.2 created.
2022-03-24 10:01:59.468  INFO 1712661 --- [           main] org.quartz.simpl.RAMJobStore             : RAMJobStore initialized.
2022-03-24 10:01:59.469  INFO 1712661 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2022-03-24 10:01:59.470  INFO 1712661 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2022-03-24 10:01:59.470  INFO 1712661 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
2022-03-24 10:01:59.541  INFO 1712661 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-03-24 10:01:59.792  INFO 1712661 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-03-24 10:01:59.880  INFO 1712661 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2022-03-24 10:02:00.076  INFO 1712661 --- [           main] c.g.s.m.a.m.handler.StartUpHandlerImpl   : databaseType=mysql，开始执行mysql的处理方法
2022-03-24 10:02:00.546  INFO 1712661 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@3b35a229, org.springframework.security.web.context.SecurityContextPersistenceFilter@5c7bfdc1, org.springframework.security.web.header.HeaderWriterFilter@126253fd, org.springframework.security.web.authentication.logout.LogoutFilter@2584b82d, com.oldwu.security.validate.ValidateCodeFilter@1f2586d6, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@1224144a, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@71687585, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@1b919693, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@9816741, org.springframework.security.web.session.SessionManagementFilter@475c9c31, org.springframework.security.web.access.ExceptionTranslationFilter@1500b2f3, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@69ee81fc]
2022-03-24 10:02:00.771  INFO 1712661 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2022-03-24 10:02:00.995  WARN 1712661 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
2022-03-24 10:02:00.997  INFO 1712661 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutting down.
2022-03-24 10:02:00.997  INFO 1712661 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
2022-03-24 10:02:00.998  INFO 1712661 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutdown complete.
2022-03-24 10:02:01.002  INFO 1712661 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-03-24 10:02:01.024  INFO 1712661 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-03-24 10:02:01.027  INFO 1712661 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-03-24 10:02:01.042  INFO 1712661 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-24 10:02:01.069 ERROR 1712661 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.15.jar!/:5.3.15]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.15.jar!/:5.3.15]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.15.jar!/:5.3.15]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_312]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.15.jar!/:5.3.15]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.15.jar!/:5.3.15]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.15.jar!/:5.3.15]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.15.jar!/:5.3.15]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) [spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) [spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) [spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.6.3.jar!/:2.6.3]
        at com.AutoPlanApplication.main(AutoPlanApplication.java:14) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [auto_plan.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [auto_plan.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [auto_plan.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [auto_plan.jar:0.0.1-SNAPSHOT]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.15.jar!/:5.3.15]
        ... 22 common frames omitted
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:238) ~[tomcat-embed-core-9.0.56.jar!/:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213) ~[spring-boot-2.6.3.jar!/:2.6.3]
        ... 24 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1075) ~[tomcat-embed-core-9.0.56.jar!/:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.56.jar!/:na]
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:234) ~[tomcat-embed-core-9.0.56.jar!/:na]
        ... 26 common frames omitted
Caused by: java.net.BindException: 地址已在使用
        at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_312]
        at sun.nio.ch.Net.bind(Net.java:461) ~[na:1.8.0_312]
        at sun.nio.ch.Net.bind(Net.java:453) ~[na:1.8.0_312]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222) ~[na:1.8.0_312]
        at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:273) ~[tomcat-embed-core-9.0.56.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:228) ~[tomcat-embed-core-9.0.56.jar!/:na]
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1213) ~[tomcat-embed-core-9.0.56.jar!/:na]
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1299) ~[tomcat-embed-core-9.0.56.jar!/:na]
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614) ~[tomcat-embed-core-9.0.56.jar!/:na]
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1072) ~[tomcat-embed-core-9.0.56.jar!/:na]
        ... 28 common frames omitted

请教大佬怎么解决

**Comment by wyt1215819315** [comment]
你自己启动，忘记把宝塔那个关了吧，两个相同端口自然冲突了
至于网页打不开，纯属是防火墙或者别的问题，和项目没有任何关系

**Comment by YuFengShiSan** [comment]
> 

确实 忘记 关了 运行了 但是还是打不开网页  数据库及防火墙都没问题 端口也都开了
