### ISSUE TITLE
原神签到福利签到失败

### ISSUE THREAD

**Issue by DerekH-233** [wyt1215819315/autoplan#79]
原神签到福利签到失败,已正确填写cookie..........

**Comment by MuXia-0326** [comment]
自建还是演示站

**Comment by ksweb2** [comment]
作者大大，我自建也是这个问题，很可能该是米游社福利签到出现验证码了

**Comment by MuXia-0326** [comment]
> 作者大大，我自建也是这个问题，很可能该是米游社福利签到出现验证码了

你自建是用的2.7版本吗？老版本确实有问题，最新版本修复了

**Comment by ksweb2** [comment]
是的是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 中午1:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79)




  
作者大大，我自建也是这个问题，很可能该是米游社福利签到出现验证码了
  
你自建是用的2.7版本吗？老版本确实有问题，最新版本修复了

**Comment by MuXia-0326** [comment]
> 是的是的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年9月5日(周一) 中午1:05 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79) 作者大大，我自建也是这个问题，很可能该是米游社福利签到出现验证码了 你自建是用的2.7版本吗？老版本确实有问题，最新版本修复了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我这边自建是正常的，最好是能提供一下后台的报错信息

**Comment by ksweb2** [comment]
enmm是网站运行日志嘛

**Comment by MuXia-0326** [comment]
> enmm是网站运行日志嘛

jar包的执行日志，如果不会获取的话，就没很好的办法排查问题了

**Comment by ksweb2** [comment]
啊。。。请问是那个auto_plan error log嘛

**Comment by MuXia-0326** [comment]
> 啊。。。请问是那个auto_plan error log嘛
你是怎么启动项目的？

**Comment by ksweb2** [comment]
我是上传到宝塔的java项目，然后，他就自己运行了，哈哈哈，大佬我小白一名，还请见谅，实在教不会我我自己再去捣鼓捣鼓

**Comment by MuXia-0326** [comment]
> 我是上传到宝塔的java项目，然后，他就自己运行了，哈哈哈，大佬我小白一名，还请见谅，实在教不会我我自己再去捣鼓捣鼓
那宝塔运行的话应该会有日志的吧，就这个日志就行

**Comment by ksweb2** [comment]
大佬，这个是网站错误日志和项目日志，你看是这个嘛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79)




  
我是上传到宝塔的java项目，然后，他就自己运行了，哈哈哈，大佬我小白一名，还请见谅，实在教不会我我自己再去捣鼓捣鼓
 那宝塔运行的话应该会有日志的吧，就这个日志就行

**Comment by MuXia-0326** [comment]
> 大佬，这个是网站错误日志和项目日志，你看是这个嘛
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年9月5日(周一) 下午3:06 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79) 我是上传到宝塔的java项目，然后，他就自己运行了，哈哈哈，大佬我小白一名，还请见谅，实在教不会我我自己再去捣鼓捣鼓 那宝塔运行的话应该会有日志的吧，就这个日志就行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我没用过宝塔，你贴出来就行了，还有贴之前，先测试一下你说的有问题的点

**Comment by ksweb2** [comment]
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String ";"
at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:456) ~[spring-security-web-5.6.2.jar!/:5.6.2]
at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:429) ~[spring-security-web-5.6.2.jar!/:5.6.2]
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:196) ~[spring-security-web-5.6.2.jar!/:5.6.2]
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[spring-security-web-5.6.2.jar!/:5.6.2]
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.60.jar!/:na]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0-internal]

2022-09-05 13:59:25.798 WARN 6331 --- [io-6666-exec-10] o.s.web.servlet.PageNotFound : No mapping for GET /favicon.ico
2022-09-05 14:00:02.211 ERROR 6331 --- [io-6666-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String ";"
at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:456) ~[spring-security-web-5.6.2.jar!/:5.6.2]
at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:429) ~[spring-security-web-5.6.2.jar!/:5.6.2]
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:196) ~[spring-security-web-5.6.2.jar!/:5.6.2]
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[spring-security-web-5.6.2.jar!/:5.6.2]
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.60.jar!/:na]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0-internal]

2022-09-05 14:00:02.342 WARN 6331 --- [nio-6666-exec-4] o.s.web.servlet.PageNotFound : No mapping for GET /favicon.ico
ROLE_USER
ROLE_USER
ROLE_USER
ROLE_USER
2022-09-05 14:10:11.244 INFO 6331 --- [nio-6666-exec-8] com.miyoushe.util.HttpUtils : 获取用户UID：113796888
2022-09-05 14:10:11.244 INFO 6331 --- [nio-6666-exec-8] com.miyoushe.util.HttpUtils : 当前用户名称：Mooe
2022-09-05 14:10:11.244 INFO 6331 --- [nio-6666-exec-8] com.miyoushe.util.HttpUtils : 当前用户服务器：天空岛
2022-09-05 14:10:43.126 INFO 6331 --- [ Thread-1761] com.miyoushe.sign.DailyTask : 开始执行时间[ 2022-09-05 14:10:43 ],执行环境[ Linux ]
2022-09-05 14:10:43.389 INFO 6331 --- [ Thread-1761] com.miyoushe.util.HttpUtils : 获取用户UID：113796888
2022-09-05 14:10:43.389 INFO 6331 --- [ Thread-1761] com.miyoushe.util.HttpUtils : 当前用户名称：Mooe
2022-09-05 14:10:43.389 INFO 6331 --- [ Thread-1761] com.miyoushe.util.HttpUtils : 当前用户服务器：天空岛
2022-09-05 14:10:43.732 INFO 6331 --- [ Thread-1761] com.miyoushe.util.HttpUtils : 原神签到福利成功：OK
2022-09-05 14:10:44.264 INFO 6331 --- [ Thread-1761] com.miyoushe.util.HttpUtils : 9月已签到3天
2022-09-05 14:10:44.264 INFO 6331 --- [ Thread-1761] com.miyoushe.util.HttpUtils : 2022-09-05签到获取20原石
2022-09-05 14:13:26.785 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.DailyTask : 开始执行时间[ 2022-09-05 14:13:26 ],执行环境[ Linux ]
2022-09-05 14:13:27.049 INFO 6331 --- [ Thread-1762] com.miyoushe.util.HttpUtils : 获取用户UID：113796888
2022-09-05 14:13:27.049 INFO 6331 --- [ Thread-1762] com.miyoushe.util.HttpUtils : 当前用户名称：Mooe
2022-09-05 14:13:27.049 INFO 6331 --- [ Thread-1762] com.miyoushe.util.HttpUtils : 当前用户服务器：天空岛
2022-09-05 14:13:27.390 INFO 6331 --- [ Thread-1762] com.miyoushe.util.HttpUtils : 原神签到福利成功：OK
2022-09-05 14:13:27.925 INFO 6331 --- [ Thread-1762] com.miyoushe.util.HttpUtils : 9月已签到3天
2022-09-05 14:13:27.925 INFO 6331 --- [ Thread-1762] com.miyoushe.util.HttpUtils : 2022-09-05签到获取20原石
2022-09-05 14:13:31.226 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : OK
2022-09-05 14:13:32.069 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 获取社区帖子数: 25
2022-09-05 14:13:36.882 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 浏览帖子: 5,点赞帖子: 5,分享帖子: 3
2022-09-05 14:13:36.883 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 社区签到任务开始
2022-09-05 14:13:37.188 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 社区签到失败: 签到失败或重复签到
2022-09-05 14:13:38.051 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 获取社区帖子数: 25
2022-09-05 14:13:48.321 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 浏览帖子,成功: 5,失败：0
2022-09-05 14:13:48.321 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 点赞帖子,成功: 5,失败：0
2022-09-05 14:13:48.321 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 分享帖子,成功: 3,失败：0
2022-09-05 14:13:48.321 INFO 6331 --- [ Thread-1762] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 社区签到任务完成
syntax error, expect {, actual int, pos 0, fastjson-version 1.2.83
2022-09-05 14:17:54.328 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.DailyTask : 开始执行时间[ 2022-09-05 14:17:54 ],执行环境[ Linux ]
2022-09-05 14:17:54.603 INFO 6331 --- [ Thread-1766] com.miyoushe.util.HttpUtils : 获取用户UID：113796888
2022-09-05 14:17:54.603 INFO 6331 --- [ Thread-1766] com.miyoushe.util.HttpUtils : 当前用户名称：Mooe
2022-09-05 14:17:54.603 INFO 6331 --- [ Thread-1766] com.miyoushe.util.HttpUtils : 当前用户服务器：天空岛
2022-09-05 14:17:54.942 INFO 6331 --- [ Thread-1766] com.miyoushe.util.HttpUtils : 原神签到福利成功：OK
2022-09-05 14:17:55.471 INFO 6331 --- [ Thread-1766] com.miyoushe.util.HttpUtils : 9月已签到3天
2022-09-05 14:17:55.471 INFO 6331 --- [ Thread-1766] com.miyoushe.util.HttpUtils : 2022-09-05签到获取20原石
2022-09-05 14:17:58.803 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 社区签到失败: 签到失败或重复签到
2022-09-05 14:17:59.656 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 获取社区帖子数: 24
2022-09-05 14:18:04.432 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 浏览帖子: 5,点赞帖子: 5,分享帖子: 3
2022-09-05 14:18:04.432 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 社区签到任务开始
2022-09-05 14:18:04.740 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 社区签到失败: 签到失败或重复签到
2022-09-05 14:18:05.567 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 获取社区帖子数: 25
2022-09-05 14:18:15.815 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 浏览帖子,成功: 5,失败：0
2022-09-05 14:18:15.815 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 点赞帖子,成功: 5,失败：0
2022-09-05 14:18:15.815 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 分享帖子,成功: 3,失败：0
2022-09-05 14:18:15.815 INFO 6331 --- [ Thread-1766] com.miyoushe.sign.gs.MiHoYoSignMiHoYo : 社区签到任务完成
2022-09-05 14:18:15.888 INFO 6331 --- [ Thread-1766] com.push.AbstractPush : 推送结果：{"msg":"请求成功","code":200,"data":"b5528d5c13c649c4860fdf89ee71d23b"}
ROLE_USER
ROLE_USER
ROLE_USER
ROLE_USER
ROLE_USER
2022-09-05 15:03:56.664 INFO 6331 --- [io-6666-exec-10] o.apache.coyote.http11.Http11Processor : Error parsing HTTP request header
Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x030x000x00/*0xe00x000x000x000x000x00Cookie: ]. HTTP method names must be tokens
at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.60.jar!/:na]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.60.jar!/:na]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0-internal]

ROLE_USER
ROLE_USER
ROLE_USER
ROLE_USER
ROLE_USER

**Comment by ksweb2** [comment]
这是截取的一部分

**Comment by MuXia-0326** [comment]
> 这是截取的一部分

日志来看，已经签到成功了

**Comment by ksweb2** [comment]
enmm，那我再重新搭建一下试试吧，谢谢大佬

**Comment by MuXia-0326** [comment]
> enmm，那我再重新搭建一下试试吧，谢谢大佬

你签到失败的日志没有吗？

**Comment by ksweb2** [comment]
没有大佬，都是显示成功，米有比的任务正常完成，但是福利签到显示成功实际没有

**Comment by MIKU-CL** [comment]
> > 恩，那我再听一下mm吧，谢谢大佬
> 
> 你签到失败的日志没有吗？

米游社的原神签到加验证码了

**Comment by MIKU-CL** [comment]
![~D2ZN AQHFZW@)L0L% 7XYJ](https://user-images.githubusercontent.com/36833022/188464183-561f8cd3-1bf2-4fc6-a469-e85afb2dc21b.jpg)

**Comment by ksweb2** [comment]
日志显示是签到成功，但是我也觉得是加验证码的缘故



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 晚上9:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79)




   
恩，那我再听一下mm吧，谢谢大佬
  
你签到失败的日志没有吗？
  
米游社的原神签到加验证码了

**Comment by MuXia-0326** [comment]
这种情况的话，无解，疑似米哈游添加风控，自己更改项目内的ua试试

**Comment by ksweb2** [comment]
弱弱问一下，ua哪里改😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 晚上10:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79)




 
这种情况的话，无解，疑似米哈游添加风控，自己更改项目内的ua试试

**Comment by MuXia-0326** [comment]
> 弱弱问一下，ua哪里改😂

https://github.com/Womsxd/AutoMihoyoBBS
![image](https://user-images.githubusercontent.com/63834850/188523881-d8591d3d-655f-4adf-ad99-472ea7c66d15.png)

这是获取设备ua的方法，至于改的话，自己查看源码，修改重新打包

**Comment by ksweb2** [comment]
好的谢谢大佬我去试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月6日(周二) 上午8:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79)




  
弱弱问一下，ua哪里改😂
  
https://github.com/Womsxd/AutoMihoyoBBS
 
 
这是获取设备ua的方法，至于改的话，自己查看源码，修改重新打包

**Comment by ksweb2** [comment]
大佬，我替换了autoplan-2.7\src\main\java\com\miyoushe\sign\gs\MiHoYoConfig 里的两个useragent，还是没得用，我觉得可能是服务器ip被风控了吧

**Comment by MuXia-0326** [comment]
> 大佬，我替换了autoplan-2.7\src\main\java\com\miyoushe\sign\gs\MiHoYoConfig 里的两个useragent，还是没得用，我觉得可能是服务器ip被风控了吧

那无解，这东西官方风控，你要不换服务器，要不手签

**Comment by ksweb2** [comment]
确实是，麻烦了

**Comment by ksweb2** [comment]
具体要怎么查看呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79)




  
是的是的
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年9月5日(周一) 中午1:05 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79) 作者大大，我自建也是这个问题，很可能该是米游社福利签到出现验证码了 你自建是用的2.7版本吗？老版本确实有问题，最新版本修复了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
我这边自建是正常的，最好是能提供一下后台的报错信息

**Comment by ksweb2** [comment]
好叭，不过还是谢谢大佬了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 晚上11:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wyt1215819315/autoplan] 原神签到福利签到失败 (Issue #79)




 
这个得改源码，但又不能根本上解决问题
